import torch
import torch.nn as nn
import numpy as np
from typing import Tuple, Optional, List, Dict

class HamiltonianNeuralNetwork(nn.Module):
    """
    Hamiltonian Neural Network (HNN) for Symplectic Celestial Mechanics.
    Reference: Greydanus et al., NeurIPS 2019 (Hamiltonian Neural Networks).
    
    Architecture:
      Learns the scalar Hamiltonian energy function H_theta(q, p): R^{2d} -> R.
      Time derivatives are strictly generated by Hamilton's canonical equations:
        dq/dt =  dH/dp
        dp/dt = -dH/dq
      Expressed via the Canonical Symplectic Matrix J:
        dz/dt = J * grad_z(H)
        
    Guarantees:
      1. Energy Conservation: dH/dt = (grad_z H)^T * J * (grad_z H) == 0 (by skew-symmetry of J).
      2. Symplectic Invariance: Preserves the differential 2-form dp ^ dq (Poincare Invariant).
      3. Liouville's Theorem: div(dz/dt) == 0 (Incompressible phase space flow).
    """
    def __init__(
        self,
        spatial_dim: int = 2,
        hidden_dim: int = 128,
        layers: int = 4,
        activation: str = "tanh",
    ):
        super().__init__()
        self.spatial_dim = spatial_dim
        self.state_dim = 2 * spatial_dim # z = (q, p)
        
        if activation.lower() == "tanh":
            act = nn.Tanh
        elif activation.lower() == "silu":
            act = nn.SiLU
        elif activation.lower() == "gelu":
            act = nn.GELU
        else:
            act = nn.Tanh
            
        net = [nn.Linear(self.state_dim, hidden_dim), act()]
        for _ in range(layers - 2):
            net.extend([nn.Linear(hidden_dim, hidden_dim), act()])
        net.append(nn.Linear(hidden_dim, 1, bias=False))
        self.net = nn.Sequential(*net)
        
        # Symplectic matrix J = [[0, I], [-I, 0]]
        J = torch.zeros(self.state_dim, self.state_dim)
        J[:spatial_dim, spatial_dim:] = torch.eye(spatial_dim)
        J[spatial_dim:, :spatial_dim] = -torch.eye(spatial_dim)
        self.register_buffer("J", J)
        self._init_weights()

    def _init_weights(self):
        for m in self.net.modules():
            if isinstance(m, nn.Linear):
                nn.init.orthogonal_(m.weight, gain=1.0)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def hamiltonian(self, z: torch.Tensor) -> torch.Tensor:
        """Predicts scalar energy H_theta(z) where z = (q, p)."""
        return self.net(z)

    def time_derivative(self, z: torch.Tensor, create_graph: bool = True) -> torch.Tensor:
        """
        Computes symplectic time derivatives dz/dt = J * grad_z(H) via Autograd.
        Uses torch.enable_grad() so evaluation works inside torch.no_grad() contexts.
        """
        with torch.enable_grad():
            if not z.requires_grad:
                z_eval = z.clone().detach().requires_grad_(True)
            else:
                z_eval = z
                
            H = self.hamiltonian(z_eval)
            grad_H = torch.autograd.grad(
                H, z_eval, grad_outputs=torch.ones_like(H), create_graph=create_graph, retain_graph=True
            )[0]
            
            dq_dt = grad_H[:, self.spatial_dim:]
            dp_dt = -grad_H[:, :self.spatial_dim]
            return torch.cat([dq_dt, dp_dt], dim=-1)

    def integrate_symplectic_rk4(
        self, z0: torch.Tensor, t_span: torch.Tensor
    ) -> torch.Tensor:
        """
        4th-Order Classical / Symplectic trajectory integrator.
        Integrates dz/dt = J * grad H along t_span.
        """
        if z0.dim() == 1:
            z0 = z0.unsqueeze(0)
            
        traj = [z0.clone()]
        curr_z = z0.clone()
        
        dt_vals = t_span[1:] - t_span[:-1]
        for dt in dt_vals:
            dt_step = dt.item()
            k1 = self.time_derivative(curr_z, create_graph=False)
            k2 = self.time_derivative(curr_z + 0.5 * dt_step * k1, create_graph=False)
            k3 = self.time_derivative(curr_z + 0.5 * dt_step * k2, create_graph=False)
            k4 = self.time_derivative(curr_z + dt_step * k3, create_graph=False)
            
            curr_z = curr_z + (dt_step / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
            traj.append(curr_z.clone())
            
        return torch.stack(traj, dim=0) # (T, B, 2d)
